name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: '47 5 7 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: Run cargo check
        run: cargo check

      - name: Run cargo build
        run: cargo build --verbose

      - name: Run cargo test
        run: cargo test --verbose

      - name: Run cargo fmt
        run: cargo fmt -- --check
        continue-on-error: false

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings -D clippy::all -W clippy::pedantic -W clippy::nursery
